CREATE DATABASE CAR_RENTAL_DB;


USE CAR_RENTRAL_DB;
CREATE TABLE USER_DETAILS(
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    GENDER ENUM('MALE', 'FEMALE') NOT NULL,
    EMAIL VARCHAR(150) UNIQUE NOT NULL,
    PHONE VARCHAR(20) UNIQUE NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    ROLE ENUM('customer', 'admin', 'rental-agent') DEFAULT 'customer',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE USER_ACCOUNT(
    ACCOUNT_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    STATUS ENUM('ACTIVE', 'INACTIVE') DEFAULT 'ACTIVE',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER_DETAILS(USER_ID) ON DELETE CASCADE
);




CREATE TABLE CAR_DETAILS (
    CAR_ID INT AUTO_INCREMENT PRIMARY KEY,
    CAR_NAME VARCHAR(50) NOT NULL,
    COLOR VARCHAR(50) NOT NULL,
    THUMBNAIL_PATH VARCHAR(255),
    CAPACITY TINYINT NOT NULL,
    STATUS ENUM('AVAILABLE', 'RESERVED', 'RENTED', 'MAINTENANCE', 'SALVAGE') DEFAULT 'AVAILABLE',
    PRICE DECIMAL(10,2) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO CAR_DETAILS (CAR_NAME, COLOR, THUMBNAIL_PATH, CAPACITY, PRICE)
VALUES
('Mitsubishi XPANDER GLS 1.5 AT 2022', 'Sterling Silver Metallic', '../../src/images/carsImage/Mitsubishi XPANDER GLS 1.5 AT 2022.png', 7, 3000.00),
('Mitsubishi XPANDER GLS 1.5 AT 2023', 'Red Metallic', '../../src/images/carsImage/Mitsubishi XPANDER GLS 1.5 AT 2023.png', 7, 3000.00),
('INNOVA 2.8 XE 2022', 'BLACK', '../../src/images/carsImage/INNOVA 2.8 XE 2022.png', 7, 3000.00),
('Toyota Vios XLE 2022', 'Blue Mica Metallic', '../../src/images/carsImage/Toyota Vios XLE 2022.png', 5, 2000.00),
('Toyota Vios XE 2019', 'Alumina Jade Green', '../../src/images/carsImage/Toyota Vios XE 2019.png', 5, 2000.00),
('Toyota Vios XE 2022', 'Pearl White', '../../src/images/carsImage/Toyota Vios XE 2022.png', 5, 2000.00);




CREATE TABLE CAR_RENTED_COUNT(
    COUNT_ID INT AUTO_INCREMENT PRIMARY KEY,
    CAR_ID INT NOT NULL,
    BOOKING_ID INT NOT NULL,
    FOREIGN KEY(CAR_ID) REFERENCES CAR_DETAILS(CAR_ID),
    FOREIGN KEY(BOOKING_ID) REFERENCES CUSTOMER_BOOKING_DETAILS(BOOKING_ID)
);




CREATE TABLE CUSTOMER_BOOKING_DETAILS (
    BOOKING_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,               -- Taken from session
    CAR_ID INT NOT NULL,                -- Selected car
    PICKUP_DATE DATETIME NOT NULL,
    DROP_OFF_DATE DATETIME NOT NULL,
    TRIP_DETAILS VARCHAR(255) NULL,   
    STATUS ENUM('PENDING', 'CANCELED', 'FOR VERIFICATION', 'FOR PICKUP', 'ONGOING', 'EXTENDED','CHECKING', 'COMPLETED') DEFAULT 'PENDING',
    TOTAL_COST  DECIMAL(10,2) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER_DETAILS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (CAR_ID) REFERENCES CAR_DETAILS(CAR_ID) ON DELETE CASCADE
);






CREATE TABLE BOOKING_PAYMENT_DETAILS(
    PAYMENT_DETAILS_ID INT AUTO_INCREMENT PRIMARY KEY,
RECEIPT_PATH VARCHAR(255) not null,
BOOKING_ID INT NOT NULL,
PAYMENT_TYPE ENUM('BOOKING FEE', 'PENALTY') DEFAULT 'BOOKING FEE'
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BOOKING_ID) REFERENCES CUSTOMER_BOOKING_DETAILS(BOOKING_ID)
);