-- ADJUSTED
CREATE TABLE USER_DETAILS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    GENDER ENUM('MALE', 'FEMALE') NOT NULL,
    EMAIL VARCHAR(150) UNIQUE NOT NULL,
    PHONE VARCHAR(20) UNIQUE NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    BIRTHDATE DATE NOT NULL,  -- user's date of birth
    ID_PATH VARCHAR(255) NULL,  -- file path for uploaded ID image (e.g., driver’s license)
    ROLE ENUM('customer', 'admin', 'rental-agent') DEFAULT 'customer',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- ADJUSTED
CREATE TABLE USER_ACCOUNT(
    ACCOUNT_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    STATUS ENUM('ACTIVE', 'INACTIVE','DECLINED') DEFAULT 'INACTIVE',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER_DETAILS(USER_ID) ON DELETE CASCADE
);

-- ADJUSTED
CREATE TABLE CAR_DETAILS (
    CAR_ID INT AUTO_INCREMENT PRIMARY KEY,
    CAR_NAME VARCHAR(50) NOT NULL,
    COLOR VARCHAR(50) NOT NULL,
    THUMBNAIL_PATH VARCHAR(255),
    CAPACITY TINYINT NOT NULL,
    STATUS ENUM('AVAILABLE', 'RESERVED', 'RENTED', 'MAINTENANCE', 'SALVAGE') DEFAULT 'AVAILABLE',
    PRICE DECIMAL(10,2) NOT NULL,
    PLATE_NUM VARCHAR(50) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE CUSTOMER_BOOKING_DETAILS (
    BOOKING_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,               -- Taken from session
    CAR_ID INT NOT NULL,                -- Selected car
    PICKUP_DATE DATETIME NOT NULL,
    DROP_OFF_DATE DATETIME NOT NULL,
    TRIP_DETAILS VARCHAR(255) NULL,
    CAR_STATUS_NOTE TEXT DEFAULT NULL,
    CAR_STATUS_IMAGE VARCHAR(255) NULL, -- Added: path or filename of status image
    STATUS ENUM('PENDING', 'CANCELED', 'FOR VERIFICATION', 'FOR PICKUP', 'ONGOING', 'EXTENDED', 'CHECKING', 'COMPLETED') DEFAULT 'PENDING',
    TOTAL_COST DECIMAL(10,2) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER_DETAILS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (CAR_ID) REFERENCES CAR_DETAILS(CAR_ID) ON DELETE CASCADE
);


-- NEW
CREATE TABLE BOOKING_STATUS_LOGS (
    LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
    BOOKING_ID INT NOT NULL,
    PREVIOUS_STATUS ENUM('PENDING', 'CANCELED', 'FOR VERIFICATION', 'FOR PICKUP', 'ONGOING', 'EXTENDED', 'CHECKING', 'COMPLETED'),
    NEW_STATUS ENUM('PENDING', 'CANCELED', 'FOR VERIFICATION', 'FOR PICKUP', 'ONGOING', 'EXTENDED', 'CHECKING', 'COMPLETED') NOT NULL,
    CHANGED_BY INT NULL,  -- NULL if system-triggered if by manager logs id from session
    CHANGE_SOURCE ENUM('SYSTEM', 'USER') DEFAULT 'USER',  -- identifies who made the change
    REMARKS VARCHAR(255) NULL,
    CHANGED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BOOKING_ID) REFERENCES CUSTOMER_BOOKING_DETAILS(BOOKING_ID) ON DELETE CASCADE,
    FOREIGN KEY (CHANGED_BY) REFERENCES USER_DETAILS(USER_ID) ON DELETE SET NULL
);


CREATE TABLE BOOKING_PAYMENT_DETAILS(
    PAYMENT_DETAILS_ID INT AUTO_INCREMENT PRIMARY KEY,
RECEIPT_PATH VARCHAR(255) not null,
BOOKING_ID INT NOT NULL,
PAYMENT_TYPE ENUM('BOOKING FEE', 'PENALTY') DEFAULT 'BOOKING FEE',
AMOUNT DECIMAL(10,2) NOT NULL DEFAULT 0,
STATUS ENUM('UNPAID', 'PAID') DEFAULT 'UNPAID',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BOOKING_ID) REFERENCES CUSTOMER_BOOKING_DETAILS(BOOKING_ID)  ON DELETE CASCADE
);
CREATE TABLE BOOKING_VEHICLE_INSPECTION (
    INSPECTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    BOOKING_ID INT NOT NULL,
    IMAGE_PATH VARCHAR(255) not null,
    USER_ID INT NOT null,
    NOTES TEXT,
 TYPE ENUM('BEFORE', 'AFTER') DEFAULT 'AFTER',
    PENALTY DECIMAL(10,2) DEFAULT 0,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BOOKING_ID) REFERENCES CUSTOMER_BOOKING_DETAILS(BOOKING_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USER_DETAILS(USER_ID)ON DELETE CASCADE
);



INSERT INTO CAR_DETAILS (CAR_NAME, COLOR, THUMBNAIL_PATH, CAPACITY, PRICE, PLATE_NUM)
VALUES
('Mitsubishi XPANDER GLS 1.5 AT 2022', 'Sterling Silver Metallic', '../../src/images/carsImage/Mitsubishi XPANDER GLS 1.5 AT 2022.png', 7, 3000.00, 'ABC-1234'),
('Mitsubishi XPANDER GLS 1.5 AT 2023', 'Red Metallic', '../../src/images/carsImage/Mitsubishi XPANDER GLS 1.5 AT 2023.png', 7, 3000.00, 'XYZ-5678'),
('INNOVA 2.8 XE 2022', 'BLACK', '../../src/images/carsImage/INNOVA 2.8 XE 2022.png', 7, 3000.00, 'LMN-9123'),
('Toyota Vios XLE 2022', 'Blue Mica Metallic', '../../src/images/carsImage/Toyota Vios XLE 2022.png', 5, 2000.00, 'DEF-3456'),
('Toyota Vios XE 2019', 'Alumina Jade Green', '../../src/images/carsImage/Toyota Vios XE 2019.png', 5, 2000.00, 'GHI-7890'),
('Toyota Vios XE 2022', 'Pearl White', '../../src/images/carsImage/Toyota Vios XE 2022.png', 5, 2000.00, 'JKL-6543');



