CREATE DATABASE CAR_RENTAL_DB;


USE CAR_RENTRAL_DB;
CREATE TABLE USER_DETAILS(
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    GENDER ENUM('MALE', 'FEMALE') NOT NULL,
    EMAIL VARCHAR(150) UNIQUE NOT NULL,
    PHONE VARCHAR(20) UNIQUE NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    ROLE ENUM('customer', 'admin', 'rental-agent') DEFAULT 'customer',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE USER_ACCOUNT(
    ACCOUNT_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    STATUS ENUM('ACTIVE', 'INACTIVE') DEFAULT 'ACTIVE',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER_DETAILS(USER_ID) ON DELETE CASCADE
);




CREATE TABLE CAR_DETAILS (
    CAR_ID INT AUTO_INCREAMENT PRIMARY KEY,
    CAR_NAME VARCHAR(50) NOT NULL,
    COLOR VARCHAR(50) NOT NULL,
    TRANSMISSION ENUM('automatic', 'manual') NOT NULL,
    CAPACITY TINYINT NOT NULL,
    STATUS ENUM('AVAILABLE', 'RESERVED', 'RENTED', 'MAINTENANCE', 'SALVAGE'),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CAR_STATUS









CREATE CUSTOMER_BOOKING_DETAILS(
    BOOKING_ID INT AUTO_INCREAMENT PRIMARY KEY,
    EMAIL VARCHAR(150) NOT NULL,
    PICKUP_DATE DATETIME NOT NULL,
    DROP_OFF_DATE DATETIME NOT NULL,
    RENTAL_OPTION ENUM('SELF DRIVE', 'WITH DRIVER') DEFAULT 'SELF DRIVER'
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EMAIL) REFERENCES CUSTOMER_DETAILS(EMAIL)
);
CREATE BOOKING_PAYMENT_DETAILS(
    PAYMENT_DETRAILS_ID INT AUTO_INCREAMENT PRIMARY KEY,
    EMAIL VARCHAR(150) NOT NULL,
    PAYMENT_OPTION ENUM('PAY NOW', 'PAY LATER') DEFAULT 'PAY LATER',
    TRANS_TYPE ENUM('CASH', 'E-PAYMENT') DEFAULT 'CASH',
    FOREIGN KEY (EMAIL) REFERENCES CUSTOMER_DETAILS(EMAIL)
);