<?php
session_start();
include "../config/db.php";

// Optional: filter by month
$month = $_GET['month'] ?? date('Y-m');
$startDate = "$month-01";
$endDate = date("Y-m-t", strtotime($startDate));

// Fetch completed bookings
$completedStmt = $conn->prepare("SELECT COUNT(*) AS total_completed, SUM(TOTAL_COST) AS total_income 
    FROM CUSTOMER_BOOKING_DETAILS 
    WHERE STATUS='COMPLETED' AND DATE(CREATED_AT) BETWEEN ? AND ?");
$completedStmt->execute([$startDate, $endDate]);
$completed = $completedStmt->fetch(PDO::FETCH_ASSOC);

// Fetch penalties
$penaltyStmt = $conn->prepare("SELECT COUNT(*) AS penalty_count, SUM(PENALTY) AS total_penalty 
    FROM BOOKING_VEHICLE_INSPECTION 
    WHERE PENALTY > 0 AND DATE(CREATED_AT) BETWEEN ? AND ?");
$penaltyStmt->execute([$startDate, $endDate]);
$penalties = $penaltyStmt->fetch(PDO::FETCH_ASSOC);
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Sales Summary Report</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="bg-gray-100 p-6">
    <div class="invoice-container max-w-3xl mx-auto bg-white p-8 border border-gray-300 shadow-md">

        <!-- Header -->
        <div class="flex justify-between items-center mb-6">
            <h1 class="text-3xl font-serif tracking-widest uppercase">Sales Summary Report</h1>
            <div class="text-right text-gray-700">
                <p>Month: <?php echo date('F Y', strtotime($startDate)); ?></p>
                <p>Generated: <?php echo date("F d, Y"); ?></p>
            </div>
        </div>

        <hr class="border-gray-400 mb-6">

        <!-- Download Button -->
        <div class="flex justify-end mb-4">
            <button id="downloadPDF" class="bg-green-600 hover:bg-green-700 text-white px-4 py-2 text-sm rounded shadow">
                Download PDF
            </button>
        </div>

        <!-- Report Table -->
        <div class="mb-6 text-sm">
            <table class="w-full border border-gray-400 border-collapse">
                <thead class="bg-gray-100">
                    <tr>
                        <th class="border border-gray-400 px-3 py-2 text-left">Report Item</th>
                        <th class="border border-gray-400 px-3 py-2 text-right">Total</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="border border-gray-400 px-3 py-2">Total Completed Bookings</td>
                        <td class="border border-gray-400 px-3 py-2 text-right"><?php echo $completed['total_completed'] ?? 0; ?></td>
                    </tr>
                    <tr>
                        <td class="border border-gray-400 px-3 py-2">Total Sale Income</td>
                        <td class="border border-gray-400 px-3 py-2 text-right">₱<?php echo number_format($completed['total_income'] ?? 0, 2); ?></td>
                    </tr>
                    <tr>
                        <td class="border border-gray-400 px-3 py-2">Total Penalty Count</td>
                        <td class="border border-gray-400 px-3 py-2 text-right"><?php echo $penalties['penalty_count'] ?? 0; ?></td>
                    </tr>
                    <tr>
                        <td class="border border-gray-400 px-3 py-2">Total Penalty Amount</td>
                        <td class="border border-gray-400 px-3 py-2 text-right">₱<?php echo number_format($penalties['total_penalty'] ?? 0, 2); ?></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <!-- Footer -->
        <div class="mt-8 text-center text-gray-500 text-sm">
            Generated by CarRental System
        </div>
    </div>

    <!-- jsPDF & html2canvas -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>

    <script>
        document.getElementById("downloadPDF").addEventListener("click", async () => {
            const {
                jsPDF
            } = window.jspdf;
            const report = document.querySelector(".invoice-container");

            // hide button during capture
            document.getElementById("downloadPDF").style.display = "none";

            const canvas = await html2canvas(report, {
                scale: 3
            });
            const imgData = canvas.toDataURL("image/png");

            const pdf = new jsPDF("p", "mm", "a4");
            const pdfWidth = pdf.internal.pageSize.getWidth();
            const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

            pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
            pdf.save("SalesSummary_<?php echo $month ?>.pdf");

            // show button again
            document.getElementById("downloadPDF").style.display = "block";
        });
    </script>

</body>

</html>